-- 코드를 입력하세요
SELECT DISTINCT(YOGURT.CART_ID)
FROM
    (SELECT *
     FROM CART_PRODUCTS
     WHERE NAME='YOGURT'
    ) AS YOGURT
JOIN
    (SELECT *
     FROM CART_PRODUCTS
     WHERE NAME='MILK'
    ) AS MILK
ON YOGURT.CART_ID=MILK.CART_ID
ORDER BY 1



# SELECT CART_ID
# FROM CART_PRODUCTS
# WHERE NAME IN ('Milk', 'Yogurt')
# GROUP BY CART_ID
# HAVING COUNT(DISTINCT NAME) = 2
# ORDER BY CART_ID