SELECT 
    year(os.SALES_DATE) AS YEAR,
    month(os.SALES_DATE) AS MONTH,
    count(distinct(os.USER_ID)) AS PUCHASED_USERS,
    ROUND((COUNT(DISTINCT OS.USER_ID) / 
           (SELECT COUNT(*) FROM USER_INFO WHERE JOINED >= '2021-01-01' AND JOINED <= '2021-12-31')), 1) AS PUCHASED_RATIO
FROM ONLINE_SALE AS OS
    INNER JOIN USER_INFO AS UI ON OS.USER_ID = UI.USER_ID
WHERE 
    UI.JOINED >='2021-01-01' AND UI.JOINED <= '2021-12-31'
GROUP BY
    YEAR, MONTH
ORDER BY
    YEAR, MONTH