SELECT 
    year(OS.SALES_DATE) AS YEAR,
    month(OS.SALES_DATE) AS MONTH,
    COUNT(DISTINCT(os.USER_ID)),
    ROUND((COUNT(DISTINCT OS.USER_ID) / 
           (SELECT COUNT(*) FROM USER_INFO WHERE JOINED >= '2021-01-01' AND JOINED <= '2021-12-31')), 1)
FROM ONLINE_SALE AS OS
    INNER JOIN USER_INFO AS UI ON OS.USER_ID = UI.USER_ID
WHERE 
    YEAR(UI.JOINED)=2021
GROUP BY
    YEAR, MONTH
ORDER BY
    YEAR, MONTH