-- 코드를 입력하세요
SELECT 
    FP.PRODUCT_ID, 
    FP.PRODUCT_NAME, 
    SUM(FP.PRICE * FO.AMOUNT) AS TOTAL
FROM FOOD_PRODUCT AS FP
    JOIN FOOD_ORDER AS FO ON FP.PRODUCT_ID=FO.PRODUCT_ID
WHERE
    FO.PRODUCE_DATE>='2022-05-01' AND FO.PRODUCE_DATE<='2022-05-31'
GROUP BY FO.PRODUCT_ID

ORDER BY
    TOTAL DESC, FP.PRODUCT_ID ASC