# -- 코드를 입력하세요
# WITH APPOINT AS (
#     SELECT *
#     FROM APPOINTMENT
#     WHERE MCDP_CD = 'CS'
#     AND APNT_CNCL_YN = 'N'
#     # AND (APNT_YMD BETWEEN '2022-04-13 00:00:00' AND '2022-04-13 23:59:59')
#     AND APNT_YMD LIKE '%2022-04-13%'
# )
# SELECT A.APNT_NO, P.PT_NAME, P.PT_NO, A.MCDP_CD, D.DR_NAME, 
#     DATE_FORMAT(A.APNT_YMD,"%Y-%m-%d %H:%i:%s.%f") as APNT_YMD
# FROM APPOINT A
# JOIN DOCTOR D ON A.MDDR_ID = D.DR_ID
# JOIN PATIENT P ON A.PT_NO = P.PT_NO
# ORDER BY A.APNT_YMD ASC;

SELECT APNT_NO
    , PT_NAME
    , PATIENT.PT_NO
    , APPOINTMENT.MCDP_CD
    , (select DR_NAME from DOCTOR where DR_ID = MDDR_ID) as DR_NAME 
    , APNT_YMD
FROM APPOINTMENT
INNER JOIN PATIENT 
    ON APPOINTMENT.PT_NO = PATIENT.PT_NO
WHERE 1=1
AND LEFT(APNT_YMD,10) = '2022-04-13'
AND APNT_CNCL_YN = 'N'
AND APPOINTMENT.MCDP_CD = 'CS'
ORDER BY APNT_YMD