-- 코드를 작성해주세요
WITH AV_SCORE AS (
    SELECT EMP_NO, AVG(SCORE) AS SCORE
    FROM HR_GRADE
    GROUP BY EMP_NO
)

SELECT
    E.EMP_NO, E.EMP_NAME, 
    CASE
        WHEN S.SCORE >= 96 THEN 'S'
        WHEN S.SCORE >= 90 THEN 'A'
        WHEN S.SCORE >= 80 THEN 'B'
        ELSE 'C'
    END AS GRADE,
    CASE
        WHEN S.SCORE >= 96 THEN (SAL*0.2)
        WHEN S.SCORE >= 90 THEN (SAL*0.15)
        WHEN S.SCORE >= 80 THEN (SAL*0.1)
        ELSE 0
    END AS BONUS
FROM HR_EMPLOYEES E
    JOIN AV_SCORE S ON E.EMP_NO = S.EMP_NO
ORDER BY 1;
