-- 코드를 입력하세요
# SELECT * 
# FROM MEMBER_PROFILE AS MP
#     JOIN REST_REVIEW AS RR ON MP.MEMBER_ID=RR.MEMBER_ID
# WHERE MP.MEMBER_ID IN (
#     SELECT MEMBER_ID
#     FROM REST_REVIEW
#     GROUP BY MEMBER_ID
#     ORDER BY COUNT(*) DESC
#     LIMIT 1
# )
# GROUP BY MP.MEMBER_ID

SELECT MP.MEMBER_NAME, RR.REVIEW_TEXT, DATE_FORMAT(RR.REVIEW_DATE, '%Y-%m-%d')
FROM MEMBER_PROFILE AS MP
    JOIN (
        SELECT RR.MEMBER_ID
        FROM REST_REVIEW AS RR
        GROUP BY RR.MEMBER_ID
        ORDER BY COUNT(*) DESC
        LIMIT 1) AS SUB ON MP.MEMBER_ID = SUB.MEMBER_ID
    JOIN REST_REVIEW AS RR ON MP.MEMBER_ID = RR.MEMBER_ID
ORDER BY RR.REVIEW_DATE, RR.REVIEW_TEXT

