-- 코드를 작성해주세요
SELECT C.ID, C.GENOTYPE, P.GENOTYPE AS PARENT_GENOTYPE
FROM ECOLI_DATA P
 JOIN ECOLI_DATA C ON P.ID = C.PARENT_ID
WHERE P.GENOTYPE | C.GENOTYPE = C.GENOTYPE
# WHERE P.GENOTYPE & C.GENOTYPE = C.GENOTYPE
ORDER BY 1;