-- 코드를 작성해주세요
# SELECT *
# FROM DEVELOPERS D
# JOIN SKILLCODES S ON D.SKILL_CODE & S.CODE
# WHERE S.SKILL_NAME = "Python" AND S.SKILL_NAME = "C#"
# ORDER BY 1;


SELECT ID, EMAIL, FIRST_NAME, LAST_NAME
FROM DEVELOPERS
WHERE SKILL_CODE & (SELECT CODE
                   FROM SKILLCODES
                   WHERE NAME = "Python")
    OR SKILL_CODE & (SELECT CODE
                    FROM SKILLCODES
                    WHERE NAME = "C#")
ORDER BY 1;