-- 코드를 작성해주세요
WITH YEAR_OF_MAX_SIZE AS (
    SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, MAX(SIZE_OF_COLONY) AS MAX_SIZE
    FROM ECOLI_DATA
    GROUP BY YEAR(DIFFERENTIATION_DATE)
)

SELECT 
    M.YEAR, M.MAX_SIZE-E.SIZE_OF_COLONY AS YEAR_DEV, E.ID
FROM ECOLI_DATA E
JOIN YEAR_OF_MAX_SIZE M ON YEAR(E.DIFFERENTIATION_DATE) = M.YEAR
ORDER BY 1, 2;